var Handlebars={};
(function(b,l){b.VERSION="1.0.0-rc.4";b.COMPILER_REVISION=3;b.REVISION_CHANGES={1:"<= 1.0.rc.2",2:"== 1.0.0-rc.3",3:">= 1.0.0-rc.4"};b.helpers={};b.partials={};var k=Object.prototype.toString;b.registerHelper=function(a,c,d){if("[object Object]"===k.call(a)){if(d||c)throw new b.Exception("Arg not supported with multiple helpers");b.Utils.extend(this.helpers,a)}else d&&(c.not=d),this.helpers[a]=c};b.registerPartial=function(a,c){"[object Object]"===k.call(a)?b.Utils.extend(this.partials,a):this.partials[a]=
c};b.registerHelper("helperMissing",function(a){if(2===arguments.length)return l;throw Error("Could not find property '"+a+"'");});b.registerHelper("blockHelperMissing",function(a,c){var d=c.inverse||function(){},e=c.fn,f=k.call(a);"[object Function]"===f&&(a=a.call(this));return!0===a?e(this):!1===a||null==a?d(this):"[object Array]"===f?0<a.length?b.helpers.each(a,c):d(this):e(a)});b.K=function(){};b.createFrame=Object.create||function(a){b.K.prototype=a;a=new b.K;b.K.prototype=null;return a};b.logger=
{DEBUG:0,INFO:1,WARN:2,ERROR:3,level:3,methodMap:{"0":"debug",1:"info",2:"warn",3:"error"},log:function(a,c){if(b.logger.level<=a){var d=b.logger.methodMap[a];"undefined"!==typeof console&&console[d]&&console[d].call(console,c)}}};b.log=function(a,c){b.logger.log(a,c)};b.registerHelper("each",function(a,c){var d=c.fn,e=c.inverse,f=0,g="",h;c.data&&(h=b.createFrame(c.data));if(a&&"object"===typeof a)if(a instanceof Array)for(var j=a.length;f<j;f++)h&&(h.index=f),g+=d(a[f],{data:h});else for(j in a)a.hasOwnProperty(j)&&
(h&&(h.key=j),g+=d(a[j],{data:h}),f++);0===f&&(g=e(this));return g});b.registerHelper("if",function(a,c){"[object Function]"===k.call(a)&&(a=a.call(this));return!a||b.Utils.isEmpty(a)?c.inverse(this):c.fn(this)});b.registerHelper("unless",function(a,c){return b.helpers["if"].call(this,a,{fn:c.inverse,inverse:c.fn})});b.registerHelper("with",function(a,c){if(!b.Utils.isEmpty(a))return c.fn(a)});b.registerHelper("log",function(a,c){var d=c.data&&null!=c.data.level?parseInt(c.data.level,10):1;b.log(d,
a)});var m="description fileName lineNumber message name number stack".split(" ");b.Exception=function(a){for(var b=Error.prototype.constructor.apply(this,arguments),d=0;d<m.length;d++)this[m[d]]=b[m[d]]};b.Exception.prototype=Error();b.SafeString=function(a){this.string=a};b.SafeString.prototype.toString=function(){return this.string.toString()};var n={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},p=/[&<>"'`]/g,q=/[&<>"'`]/,r=function(a){return n[a]||"&amp;"};b.Utils=
{extend:function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])},escapeExpression:function(a){if(a instanceof b.SafeString)return a.toString();if(null==a||!1===a)return"";a=a.toString();return!q.test(a)?a:a.replace(p,r)},isEmpty:function(a){return!a&&0!==a?!0:"[object Array]"===k.call(a)&&0===a.length?!0:!1}};b.VM={template:function(a){var c={escapeExpression:b.Utils.escapeExpression,invokePartial:b.VM.invokePartial,programs:[],program:function(a,c,f){var g=this.programs[a];f?g=b.VM.program(a,
c,f):g||(g=this.programs[a]=b.VM.program(a,c));return g},programWithDepth:b.VM.programWithDepth,noop:b.VM.noop,compilerInfo:null};return function(d,e){e=e||{};var f=a.call(c,b,d,e.helpers,e.partials,e.data),g=c.compilerInfo||[],h=g[0]||1,j=b.COMPILER_REVISION;if(h!==j){if(h<j)throw"Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version ("+b.REVISION_CHANGES[j]+") or downgrade your runtime to an older version ("+b.REVISION_CHANGES[h]+
").";throw"Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version ("+g[1]+").";}return f}},programWithDepth:function(a,b,d){var e=Array.prototype.slice.call(arguments,3),f=function(a,f){f=f||{};return b.apply(this,[a,f.data||d].concat(e))};f.program=a;f.depth=e.length;return f},program:function(a,b,d){var e=function(a,e){e=e||{};return b(a,e.data||d)};e.program=a;e.depth=0;return e},noop:function(){return""},invokePartial:function(a,
c,d,e,f,g){e={helpers:e,partials:f,data:g};if(a===l)throw new b.Exception("The partial "+c+" could not be found");if(a instanceof Function)return a(d,e);if(b.compile)return f[c]=b.compile(a,{data:g!==l}),f[c](d,e);throw new b.Exception("The partial "+c+" could not be compiled when running in runtime-only mode");}};b.template=b.VM.template})(Handlebars);
